management:
  endpoint:
    health:
      show-details: always

logging:
  level:
    skinemsya.vse.ru: DEBUG
    org.springframework.web: INFO

skinemsya:
  cors:
    allowed-origin-patterns:
      - http://localhost:*
      - http://127.0.0.1:*
      - https://web.telegram.org
      - https://*.ngrok-free.app
      - https://audacity-savor-saxophone.ngrok-free.dev
